# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

# -   repo: https://github.com/jonasbb/pre-commit-latex-hooks
#     rev: v1.5.0
#     hooks:
#     -   id: unique-labels
#     -   id: ensure-labels-for-sections
#     -   id: no-space-in-cite
#     -   id: tilde-cite
#     -   id: csquotes
#     -   id: cleveref-instead-of-autoref
